### ISSUE TITLE
Missing part 15

### ISSUE THREAD

**Issue by idiuwhatiwant** [christinec-dev/DustyTrails_RPG_Parts#1]
Hi @christinec-dev!

Thanks for setting up all of this! I've been following your `Learn Godot by Making an RPG` tutorial series as a personal refresher since I've not worked with Godot 3 for a long while and it's been a great intro to Godot 4 ❤️ 

It looks like part 15 may be missing from this repo? Page 253 of your PDF references the code to https://github.com/christinec-dev/DustyTrails_RPG_Parts/tree/main/Part_15, which doesn't exist and I couldn't seem to spot it in the commit history.

**Comment by christinec-dev** [comment]
Hey there,

I'm so sorry for the *err *on my side. I updated it - it seems I never
uploaded the files to the Part 15 folder (oops). Thank you for notifying me
of this!

Have a happy week of coding ahead. 😊

Kind regards
Christine

**Comment by idiuwhatiwant** [comment]
Awesome, thanks! @christinec-dev It looks like a new commit was pushed with the files but for the root directory - did you mean to commit them for a separate part 15 folder?

**Comment by christinec-dev** [comment]
You are correct - I fixed it. I promise I'm not doing these mistakes on
purpose, my brain is just not working with me this week (month, year,
decade?)!😅

Thanks again.

[image: image.png]

Kind regards
Christine
